#!/bin/bash

. .ntw.sh

selectNode v16.13.1
selectTool pnpm 6.26.1

if [[ "$1" == "i" ]] || [[ "$1" == "install" ]]; then
  # retry up to 3 times to account for flakiness in module downloads
  for i in $(seq 1 3); do
    pnpm "$@" && break
  done
else
  pnpm "$@"
fi
